project:
  owner: mail@example.org
  name: aws-cd-demo-1
  regions:
    - us-east-1
    - eu-west-1
    - us-west-2
    - eu-central-1
  template: ./templates/main.cf.json
  parameters:
    S3BucketName: $[taskcat_autobucket]
    S3ProjectFolderName: aws-cd-demo-1
  tags:
    deployment-source: taskcat
    deployment-type: test
    deployment-stage: dev
tests:
  default:
    regions:
      - us-east-1
    parameters:
      S3BucketRegion: us-east-1